/* This file is automatically generated and overwritten by build.gradle. */

package team.returnteamname.ehotel.config;

public interface IConfigConstant
{
    java.lang.String ROOT_PACKAGE_NAME = "team.returnteamname.ehotel";
    java.lang.String CONFIG_FILE_PATH = "config.json";
}
