/* This file is automatically generated and overwritten by build.gradle. */

package team.returnteamname.myhotelcustomer.config;

public interface IConfigConstant
{
    java.lang.String ROOT_PACKAGE_NAME = "team.returnteamname.myhotelcustomer";
}
